name: "build"
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  deploy: 
    runs-on: ubuntu-latest
    name: "Deploy react-app to github pages"
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development
          persist-credentials: false
      
      - name: use node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          check-latest: true
          registry-url: https://registry.npmjs.org/
      
      - name: npm install, build, and test
        run: |
          npm install
          npm run build 
          npm run test
    
